### GET request to example server
POST localhost:8082/api/projects
Content-Type: application/json
memberId: 8

{
  "projectName": "project16",
  "tags": [
    {"name": "tag1"},
    {"name": "tag2"}
  ]
}

###
GET localhost:8082/api/projects/by-member/8